export const KEY_DIVIDER = ':'
export const BUDGET_KEY = 'budget'
export const BUDGET_PREFIX = BUDGET_KEY + KEY_DIVIDER
export const SHORT_BUDGET_KEY = 'bud'
export const SHORT_BUDGET_PREFIX = SHORT_BUDGET_KEY + KEY_DIVIDER
export const ACC_KEY = 'account'
export const ACC_PREFIX = ACC_KEY + KEY_DIVIDER
export const TXN_KEY = 'transaction'
export const TXN_PREFIX = TXN_KEY + KEY_DIVIDER
export const INCOME_KEY = 'income'
export const CAT_KEY = 'cat'
export const CAT_PREFIX = CAT_KEY + KEY_DIVIDER
export const CAT_ITEM_KEY = 'catItem'
export const CAT_ITEM_PREFIX = CAT_ITEM_KEY + KEY_DIVIDER
export const MONTH_CAT_ITEM_KEY = 'monthCatItem'
export const MONTH_CAT_ITEM_PREFIX = MONTH_CAT_ITEM_KEY + KEY_DIVIDER
export const SCHED_EXECUTED_KEY = 'schedEx'
export const SCHED_EXECUTED_PREFIX = SCHED_EXECUTED_KEY + KEY_DIVIDER